version: "3.6"

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 9000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - DB_CONNECTION_STRING=Server=192.168.43.146;Database=Dns–°ozyHome;User Id=sa;Password=1;
    volumes:
      - ~/.aspnet/https:/https:ro